version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "siamo-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ebmpsgy83nsr"
s3_prefix = "siamo-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

